type IExchangeApolloTicketParsedMask = {
    mcoRows: [{
        command: '*MCO1',
        passengerName: 'BITCA/IU',
        documentNumber: '0065056180983',
        issueDate: {raw: '03APR19', parsed: '2019-04-03'},
        amount: '100.00',
        "fullData": {
            "passengerName": "BITCA/IURI",
            "to": "DL",
            "at": "ATL",
            "validFor": "SPLIT",
            "tourCode": "",
            "ticketNumber": "",
            "formOfPayment": {"raw": "AXXXXXXXXXXXX1052/OK"},
            "expirationMonth": "02",
            "expirationYear": "23",
            "approvalCode": "109678",
            "commission": "0.00/",
            "taxAmount": "",
            "taxCode": "",
            "baseFare": {"currency": "USD", "amount": "100.00"},
            "fareEquivalent": null,
            "rateOfExchange": "",
            "endorsementBox": "",
            "remark1": "",
            "remark2": "",
            "validatingCarrier": "DL",
            "issueNow": false
        }
    }],
    headerData: {
        lastName: string,
        firstName: string,
        majorNumber: string,
        minorNumber: string,
        baseFareCurrency: string,
        baseFareAmount: string,
        netPriceCurrency: string,
        netPriceAmount: string,
        equivalentPart: string,
        taxCurrency1: string,
        taxAmount1: string,
        taxCode1: string,
        taxCurrency2: string,
        taxAmount2: string,
        taxCode2: string,
        taxCurrency3: string,
        taxAmount3: string,
        taxCode3: string,
        exchangedTicketCurrency: string,
    }
    fields: [
        {"enabled"?: true , "key": "exchangedTicketNumber", "value": ""},
        {"enabled"?: true , "key": "exchangedTicketExtension", "value": ""},
        {"enabled"?: false, "key": "ticketNumber1", "value": "01672891061612"},
        {"enabled"?: false, "key": "couponNumber1", "value": "1"},
        {"enabled"?: true , "key": "ticketNumber2", "value": ""},
        {"enabled"?: true , "key": "couponNumber2", "value": ""},
        {"enabled"?: true , "key": "commission", "value": ""},
        {"enabled"?: false, "key": "originalFormOfPayment", "value": "CK"},
        {"enabled"?: true , "key": "evenIndicator", "value": ""},
        {"enabled"?: false, "key": "exchangedTicketTotalValue", "value": "983.30"},
        {"enabled"?: false, "key": "originalBoardPoint", "value": "SFO"},
        {"enabled"?: false, "key": "originalOffPoint", "value": "LAX"},
        {"enabled"?: false, "key": "taxAmount1", "value": "67.60"},
        {"enabled"?: false, "key": "taxCode1", "value": "US"},
        {"enabled"?: false, "key": "taxAmount2", "value": "14.30"},
        {"enabled"?: false, "key": "taxCode2", "value": "XT"},
        {"enabled"?: true , "key": "taxAmount3", "value": ""},
        {"enabled"?: true , "key": "taxCode3", "value": ""},
        {"enabled"?: false, "key": "originalIssuePoint", "value": "SFO"},
        {"enabled"?: false, "key": "originalIssueDate", "value": "02APR19"},
        {"enabled"?: false, "key": "originalAgencyIata", "value": "00000000 "},
        {"enabled"?: false, "key": "originalTicketStar", "value": "0161111111111"},
        {"enabled"?: false, "key": "originalTicketStarExtension", "value": ""},
        {"enabled"?: false, "key": "originalInvoiceNumber", "value": ""},
        {"enabled"?: true , "key": "penaltyAmount", "value": ""},
        {"enabled"?: true , "key": "commOnPenaltyAmount", "value": ""}
    ],
    maskOutput?: '>$EX NAME ...',
}
